/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ListSidebarPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/ListView.ts
var import_obsidian = require("obsidian");
var VIEW_TYPE_LIST_SIDEBAR = "list-sidebar-view";
var ListView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.lists = [];
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_LIST_SIDEBAR;
  }
  getDisplayText() {
    return "\u5217\u8868\u4FA7\u8FB9\u680F";
  }
  getIcon() {
    return "list";
  }
  async onOpen() {
    await this.loadData();
    this.render();
  }
  async onClose() {
  }
  async loadData() {
    this.lists = await this.plugin.loadLists();
  }
  async saveData() {
    await this.plugin.saveLists(this.lists);
  }
  render() {
    const container = this.containerEl.children[1];
    if (!container) {
      return;
    }
    container.empty();
    container.addClass("list-sidebar-container");
    const headerEl = container.createDiv("list-sidebar-header");
    const settingsBtn = headerEl.createEl("button", {
      text: "\u2699\uFE0F",
      cls: "list-sidebar-settings-btn",
      attr: { "aria-label": "\u8BBE\u7F6E" }
    });
    settingsBtn.onclick = () => {
      this.plugin.openSettings();
    };
    const listsContainer = container.createDiv("list-sidebar-lists");
    this.lists.forEach((list, listIndex) => {
      this.renderList(listsContainer, list, listIndex);
    });
    const addListBtn = container.createEl("button", {
      text: "+ \u6DFB\u52A0\u5217\u8868",
      cls: "list-sidebar-add-list-btn"
    });
    addListBtn.onclick = async () => {
      const name = await this.promptForInput("\u8F93\u5165\u5217\u8868\u540D\u79F0\uFF1A");
      if (name && name.trim()) {
        const newList = {
          name: name.trim(),
          expanded: true,
          items: []
        };
        this.lists.push(newList);
        await this.saveData();
        this.render();
      }
    };
  }
  renderList(container, list, listIndex) {
    const listEl = container.createDiv("list-sidebar-list");
    const headerEl = listEl.createDiv("list-sidebar-list-header");
    const toggleBtn = headerEl.createEl("button", {
      text: list.expanded ? "\u25BC" : "\u25B6",
      cls: "list-sidebar-toggle-btn",
      attr: { "aria-label": list.expanded ? "\u6298\u53E0" : "\u5C55\u5F00" }
    });
    toggleBtn.onclick = async () => {
      list.expanded = !list.expanded;
      await this.saveData();
      this.render();
    };
    const nameEl = headerEl.createEl("span", {
      text: list.name,
      cls: "list-sidebar-list-name"
    });
    const deleteListBtn = headerEl.createEl("button", {
      text: "\u{1F5D1}\uFE0F",
      cls: "list-sidebar-delete-btn",
      attr: { "aria-label": "\u5220\u9664\u5217\u8868" }
    });
    deleteListBtn.onclick = async () => {
      const confirmed = await this.showConfirmDialog(`\u786E\u5B9A\u8981\u5220\u9664\u5217\u8868"${list.name}"\u5417\uFF1F`);
      if (confirmed) {
        this.lists.splice(listIndex, 1);
        await this.saveData();
        this.render();
      }
    };
    if (list.expanded) {
      const itemsContainer = listEl.createDiv("list-sidebar-items");
      list.items.forEach((item, itemIndex) => {
        this.renderItem(itemsContainer, item, listIndex, itemIndex);
      });
      const addItemBtn = itemsContainer.createEl("button", {
        text: "+ \u6DFB\u52A0\u6761\u76EE",
        cls: "list-sidebar-add-item-btn"
      });
      addItemBtn.onclick = async () => {
        const content = await this.promptForInput("\u8F93\u5165\u6761\u76EE\u5185\u5BB9\uFF08\u652F\u6301\u7B14\u8BB0\u94FE\u63A5[[note]]\u6216\u7EAF\u6587\u672C\uFF09\uFF1A");
        if (content && content.trim()) {
          const newItem = {
            content: content.trim()
          };
          list.items.push(newItem);
          await this.saveData();
          this.render();
        }
      };
    }
  }
  renderItem(container, item, listIndex, itemIndex) {
    const itemEl = container.createDiv("list-sidebar-item");
    const contentEl = itemEl.createDiv("list-sidebar-item-content");
    const linkMatch = item.content.match(/\[\[([^\]]+)\]\]/);
    if (linkMatch) {
      const linkText = linkMatch[1];
      const linkEl = contentEl.createEl("a", {
        text: linkText,
        cls: "internal-link"
      });
      linkEl.onclick = async (e) => {
        e.preventDefault();
        const file = this.app.metadataCache.getFirstLinkpathDest(linkText, "");
        if (file) {
          await this.app.workspace.openLinkText(linkText, "", true);
        }
      };
    } else {
      contentEl.createEl("span", {
        text: item.content
      });
    }
    const deleteItemBtn = itemEl.createEl("button", {
      text: "\xD7",
      cls: "list-sidebar-delete-item-btn",
      attr: { "aria-label": "\u5220\u9664\u6761\u76EE" }
    });
    deleteItemBtn.onclick = async () => {
      this.lists[listIndex].items.splice(itemIndex, 1);
      await this.saveData();
      this.render();
    };
  }
  async promptForInput(prompt) {
    return new Promise((resolve) => {
      const modal = new InputModal(this.app, prompt, (value) => {
        resolve(value);
      });
      modal.open();
    });
  }
  async refresh() {
    await this.loadData();
    this.render();
  }
  async showConfirmDialog(message) {
    return new Promise((resolve) => {
      const modal = new ConfirmModal(this.app, message, (confirmed) => {
        resolve(confirmed);
      });
      modal.open();
    });
  }
};
var InputModal = class extends import_obsidian.Modal {
  constructor(app, prompt, onSubmit) {
    super(app);
    this.prompt = prompt;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.prompt });
    this.inputEl = contentEl.createEl("input", {
      type: "text",
      placeholder: "\u8F93\u5165\u5185\u5BB9..."
    });
    this.inputEl.focus();
    this.inputEl.select();
    const buttonContainer = contentEl.createDiv("modal-button-container");
    const submitBtn = buttonContainer.createEl("button", {
      text: "\u786E\u5B9A",
      cls: "mod-cta"
    });
    const cancelBtn = buttonContainer.createEl("button", {
      text: "\u53D6\u6D88"
    });
    submitBtn.onclick = () => {
      this.onSubmit(this.inputEl.value);
      this.close();
    };
    cancelBtn.onclick = () => {
      this.onSubmit(null);
      this.close();
    };
    this.inputEl.onkeydown = (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        submitBtn.click();
      } else if (e.key === "Escape") {
        e.preventDefault();
        cancelBtn.click();
      }
    };
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var ConfirmModal = class extends import_obsidian.Modal {
  constructor(app, message, onSubmit) {
    super(app);
    this.message = message;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("p", { text: this.message });
    const buttonContainer = contentEl.createDiv("modal-button-container");
    const confirmBtn = buttonContainer.createEl("button", {
      text: "\u786E\u5B9A",
      cls: "mod-cta"
    });
    const cancelBtn = buttonContainer.createEl("button", {
      text: "\u53D6\u6D88"
    });
    confirmBtn.onclick = () => {
      this.onSubmit(true);
      this.close();
    };
    cancelBtn.onclick = () => {
      this.onSubmit(false);
      this.close();
    };
    confirmBtn.focus();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// main.ts
var DEFAULT_SETTINGS = {
  filePath: "\u5217\u8868\u4FA7\u8FB9\u680F\u6570\u636E.md"
};
var ListSidebarPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(
      VIEW_TYPE_LIST_SIDEBAR,
      (leaf) => {
        const view = new ListView(leaf, this);
        this.listView = view;
        return view;
      }
    );
    this.addRibbonIcon("list", "\u6253\u5F00\u5217\u8868\u4FA7\u8FB9\u680F", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-list-sidebar",
      name: "\u6253\u5F00\u5217\u8868\u4FA7\u8FB9\u680F",
      callback: () => {
        this.activateView();
      }
    });
    this.addSettingTab(new ListSidebarSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      this.activateView();
    });
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_LIST_SIDEBAR);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_LIST_SIDEBAR)[0];
    if (!leaf) {
      const newLeaf = workspace.getRightLeaf(false);
      if (newLeaf) {
        await newLeaf.setViewState({ type: VIEW_TYPE_LIST_SIDEBAR, active: true });
        leaf = newLeaf;
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  async loadLists() {
    try {
      const file = this.app.vault.getAbstractFileByPath(this.settings.filePath);
      if (!file || !(file instanceof import_obsidian2.TFile)) {
        return [];
      }
      const content = await this.app.vault.read(file);
      return this.parseMarkdownFile(content);
    } catch (error) {
      console.error("\u52A0\u8F7D\u5217\u8868\u6570\u636E\u5931\u8D25:", error);
      return [];
    }
  }
  async saveLists(lists) {
    try {
      const content = this.generateMarkdownFile(lists);
      const file = this.app.vault.getAbstractFileByPath(this.settings.filePath);
      if (file && file instanceof import_obsidian2.TFile) {
        await this.app.vault.modify(file, content);
      } else {
        await this.app.vault.create(this.settings.filePath, content);
      }
    } catch (error) {
      console.error("\u4FDD\u5B58\u5217\u8868\u6570\u636E\u5931\u8D25:", error);
      const errorMessage = error instanceof Error ? error.message : String(error);
      new import_obsidian2.Notice("\u4FDD\u5B58\u5217\u8868\u6570\u636E\u5931\u8D25: " + errorMessage);
    }
  }
  parseMarkdownFile(content) {
    const lists = [];
    const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---\n/);
    let metadata = {};
    if (frontmatterMatch) {
      try {
        const yamlContent = frontmatterMatch[1];
        const lines = yamlContent.split("\n");
        let currentList = null;
        lines.forEach((line) => {
          const listMatch = line.match(/^(\w+):$/);
          if (listMatch) {
            if (currentList) {
              lists.push(currentList);
            }
            currentList = {
              name: listMatch[1],
              expanded: true,
              items: []
            };
          } else if (currentList && line.trim().startsWith("- ")) {
            const itemContent = line.trim().substring(2);
            currentList.items.push({ content: itemContent });
          } else if (line.trim().startsWith("expanded:")) {
            currentList.expanded = line.trim().substring(9).trim() === "true";
          }
        });
        if (currentList) {
          lists.push(currentList);
        }
      } catch (e) {
        console.error("\u89E3\u6790YAML\u5931\u8D25:", e);
      }
    }
    if (lists.length === 0) {
      const bodyContent = frontmatterMatch ? content.substring(frontmatterMatch[0].length) : content;
      const lines = bodyContent.split("\n");
      let currentList = null;
      lines.forEach((line) => {
        const listHeaderMatch = line.match(/^## (.+?)(\s*<!--.*?-->)?$/);
        if (listHeaderMatch) {
          if (currentList) {
            lists.push(currentList);
          }
          const listName = listHeaderMatch[1].trim();
          const expandedComment = listHeaderMatch[2] || "";
          const isExpanded = expandedComment.includes("expanded:true");
          currentList = {
            name: listName,
            expanded: isExpanded,
            items: []
          };
        } else if (currentList && line.trim().startsWith("- ")) {
          const itemContent = line.trim().substring(2);
          currentList.items.push({ content: itemContent });
        }
      });
      if (currentList) {
        lists.push(currentList);
      }
    }
    return lists.length > 0 ? lists : [];
  }
  generateMarkdownFile(lists) {
    let content = "";
    lists.forEach((list, index) => {
      if (index > 0) {
        content += "\n";
      }
      const expandedMarker = list.expanded ? "<!-- expanded:true -->" : "<!-- expanded:false -->";
      content += `## ${list.name} ${expandedMarker}

`;
      list.items.forEach((item) => {
        content += `- ${item.content}
`;
      });
    });
    return content;
  }
  openSettings() {
    this.app.setting.open();
    this.app.setting.openTabById(this.manifest.id);
  }
};
var ListSidebarSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u5217\u8868\u4FA7\u8FB9\u680F\u8BBE\u7F6E" });
    new import_obsidian2.Setting(containerEl).setName("\u6570\u636E\u6587\u4EF6\u8DEF\u5F84").setDesc("\u4FDD\u5B58\u5217\u8868\u6570\u636E\u7684Markdown\u6587\u4EF6\u8DEF\u5F84\uFF08\u76F8\u5BF9\u4E8E\u5E93\u6839\u76EE\u5F55\uFF09").addText((text) => text.setPlaceholder("\u4F8B\u5982: \u5217\u8868\u4FA7\u8FB9\u680F\u6570\u636E.md").setValue(this.plugin.settings.filePath).onChange(async (value) => {
      this.plugin.settings.filePath = value;
      await this.plugin.saveSettings();
      const listView = this.plugin.listView;
      if (listView) {
        await listView.refresh();
      }
    }));
  }
};
